DROP DATABASE IF EXISTS anishboard;

create DATABASE anishboard;


CREATE TABLE ANIME(
    ID_ANIME INT NOT NULL,
    NOMBRE_ANIME VARCHAR (200) NOT NULL,
    SINOPSIS_ANIME TEXT NOT NULL,
    NO_CAP INT NOT NULL,
    NO_CALIFICACION INT NOT NULL,
    IMG_ANIME TEXT NOT NULL,
    BANNER_ANIME TEXT NOT NULL,
    CALI_POS INT NOT NULL,
    CALI_NEG INT NOT NULL,
    PRIMARY KEY (ID_ANIME)
);